FROM golang:1.19 AS builder
WORKDIR  /go/src/github.com/openshift/oauth-proxy
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build .

FROM registry.access.redhat.com/ubi8-minimal:8.6-854
WORKDIR /root/

COPY --from=builder /go/src/github.com/openshift/oauth-proxy/oauth-proxy /usr/bin/oauth-proxy
COPY --from=builder /go/src/github.com/openshift/oauth-proxy/templates /usr/templates

ENTRYPOINT ["/usr/bin/oauth-proxy"]
