FROM registry.access.redhat.com/ubi8/go-toolset:1.17.12-3 AS builder
WORKDIR  /go/src/github.com/openshift/oauth-proxy
COPY . .
RUN go build .

FROM registry.access.redhat.com/ubi8/go-toolset:1.17.12-3
WORKDIR  /go/src/github.com/openshift/oauth-proxy
COPY . .
COPY --from=builder /go/src/github.com/openshift/oauth-proxy/oauth-proxy /usr/bin/oauth-proxy
COPY --from=builder /go/src/github.com/openshift/oauth-proxy/templates /usr/templates

ENTRYPOINT ["/usr/bin/oauth-proxy"]

